import type { StatusState } from "@/lib/types";

export const statusStates: StatusState[] = [
  {
    slug: "catalog-unavailable",
    code: "B18",
    eyebrow: "ÜRÜN KATALOĞU",
    title: "Seçilen ürün şu anda kullanılamıyor",
    description: "Bu katalog ürününü güvenli biçimde hazırlayamadık. Başka bir ürün seçebilirsin.",
    tone: "error",
    symbol: "×",
    primaryLabel: "Başka ürün seç",
    primaryHref: "/try-on",
    secondaryLabel: "Destek al",
    secondaryHref: "/support",
    detailTitle: "Güvenli ve şeffaf işlem",
    detailText: "Yalnız trAI kataloğunda doğrulanmış görseli bulunan ürünlerle AI provası başlatılır.",
    appScreen: true,
    active: "try-on",
  },
  {
    slug: "photo-upload-failed",
    code: "B16",
    eyebrow: "FOTOĞRAF YÜKLEME",
    title: "Fotoğraf yüklenemedi",
    description: "Dosyanı yüklerken bir sorun oluştu. İnternet bağlantını kontrol edip yeniden deneyebilirsin.",
    tone: "error",
    symbol: "!",
    primaryLabel: "Yeniden dene",
    primaryHref: "/try-on",
    detailTitle: "Desteklenen dosyalar",
    detailText: "JPG, PNG veya WebP biçiminde ve en fazla 6 MB fotoğraf kullan.",
    appScreen: true,
    active: "try-on",
  },
  {
    slug: "photo-quality",
    code: "B17",
    eyebrow: "FOTOĞRAF KALİTESİ",
    title: "Fotoğraf yeterince net değil",
    description: "Daha iyi bir sonuç için yüzünün ve kıyafetinin net göründüğü, iyi aydınlatılmış bir fotoğraf seç.",
    tone: "warning",
    symbol: "!",
    primaryLabel: "Yeni fotoğraf seç",
    primaryHref: "/try-on",
    detailTitle: "İyi fotoğraf ipucu",
    detailText: "Düz bir zeminde, karşıdan çekilmiş ve tüm vücudunun göründüğü bir kare kullan.",
    appScreen: true,
    active: "try-on",
  },
  {
    slug: "generation-failed",
    code: "B19",
    eyebrow: "AI PROVA",
    title: "Prova oluşturulamadı",
    description: "İşlem sırasında geçici bir hata oluştu. Güvenli biçimde yeni bir prova başlatabilirsin.",
    tone: "error",
    symbol: "×",
    primaryLabel: "Tekrar oluştur",
    primaryHref: "/try-on",
    detailTitle: "Ne yapabilirsin?",
    detailText: "Önce fotoğrafını ve seçtiğin katalog ürününü kontrol et; sorun sürerse destek ekibine hata mesajını ilet.",
    appScreen: true,
    active: "try-on",
  },
  {
    slug: "generation-timeout",
    code: "B20",
    eyebrow: "İŞLEM SÜRESİ",
    title: "İşlem beklenenden uzun sürdü",
    description: "Prova arka planda tamamlanıyor olabilir. Biraz sonra tekrar kontrol edebilirsin.",
    tone: "warning",
    symbol: "…",
    primaryLabel: "Durumu kontrol et",
    primaryHref: "/try-on",
    detailTitle: "Verilerin güvende",
    detailText: "Yeni bir işlem başlatmadan önce mevcut isteğin sonucunu kontrol et.",
    appScreen: true,
    active: "try-on",
  },
  {
    slug: "offline",
    code: "E01",
    eyebrow: "BAĞLANTI",
    title: "İnternet bağlantısı yok",
    description: "Bağlantın geri geldiğinde kaldığın yerden devam edebilirsin.",
    tone: "offline",
    symbol: "↻",
    primaryLabel: "Tekrar dene",
    primaryHref: "/try-on",
    detailTitle: "Yükleme başlamadı",
    detailText: "Bağlantı geri geldiğinde fotoğrafını yeniden seçmen gerekebilir; tamamlanmamış dosyalar prova için kullanılmaz.",
    appScreen: true,
    active: "try-on",
  },
  {
    slug: "session-expired",
    code: "E02",
    eyebrow: "OTURUM",
    title: "Oturumun sona erdi",
    description: "Oturum süren dolduğu için devam etmeden önce yeniden giriş yapmalısın.",
    tone: "warning",
    symbol: "!",
    primaryLabel: "Tekrar giriş yap",
    primaryHref: "/login",
    detailTitle: "Güvenli oturum",
    detailText: "Kaydedilmiş kombinlerin ve ölçülerin hesabında durmaya devam eder.",
    appScreen: false,
  },
  {
    slug: "password-reset-complete",
    code: "A07",
    eyebrow: "ŞİFRE",
    title: "Şifren yenilendi",
    description: "Yeni şifrenle hesabına güvenle giriş yapabilirsin.",
    tone: "success",
    symbol: "✓",
    primaryLabel: "Giriş yap",
    primaryHref: "/login",
    detailTitle: "İşlem tamamlandı",
    detailText: "Diğer açık oturumların güvenlik amacıyla kapatıldı.",
    appScreen: false,
  },
  {
    slug: "invalid-reset-link",
    code: "A09",
    eyebrow: "ŞİFRE BAĞLANTISI",
    title: "Bu bağlantı artık geçerli değil",
    description: "Şifre yenileme bağlantısının süresi dolmuş veya daha önce kullanılmış olabilir.",
    tone: "error",
    symbol: "×",
    primaryLabel: "Yeni bağlantı iste",
    primaryHref: "/forgot-password",
    detailTitle: "Güvenlik bilgisi",
    detailText: "Şifre bağlantıları yalnızca bir kez ve sınırlı süre boyunca kullanılabilir.",
    appScreen: false,
  },
  {
    slug: "quota-reached",
    code: "E06",
    eyebrow: "PROVA HAKKI",
    title: "Seçimin kalan hakkını aşıyor",
    description: "Her beden ve görünüm ayrı bir çıktı sayılır. Daha az çıktı seçebilir veya hesap bilgini kontrol edebilirsin.",
    tone: "warning",
    symbol: "!",
    primaryLabel: "Provaya dön",
    primaryHref: "/try-on",
    secondaryLabel: "Hesabı kontrol et",
    secondaryHref: "/settings",
    detailTitle: "Mevcut içeriklerin korunur",
    detailText: "Kota yalnızca yeni prova üretimini sınırlar.",
    appScreen: true,
    active: "try-on",
  },
  {
    slug: "empty-looks",
    code: "C09",
    eyebrow: "KOMBİNLERİM",
    title: "Henüz kayıtlı kombinin yok",
    description: "Beğendiğin prova sonuçlarını kaydet; görünümleri incele ve ürün sayfasına buradan geri dön.",
    tone: "empty",
    symbol: "+",
    primaryLabel: "Yeni prova oluştur",
    primaryHref: "/try-on",
    detailTitle: "İlk kombinini oluştur",
    detailText: "Bir prova sonucunu kaydettiğinde otomatik olarak bu listede görünür.",
    appScreen: true,
    active: "looks",
  },
  {
    slug: "account-deletion",
    code: "D10",
    eyebrow: "GERİ ALINAMAZ İŞLEM",
    title: "Hesabını kalıcı olarak sil?",
    description: "Hesabın, fotoğrafların ve kaydettiğin tüm sonuçlar silinecek. Bu işlem geri alınamaz.",
    tone: "error",
    symbol: "!",
    primaryLabel: "Vazgeç",
    primaryHref: "/settings",
    secondaryLabel: "Destek al",
    secondaryHref: "/support",
    detailTitle: "Silinecek içerikler",
    detailText: "Hesap bilgileri, kayıtlı prova sonuçları, kombinler, özel fotoğraflar ve beden ölçüleri.",
    appScreen: true,
    active: "profile",
  },
  {
    slug: "account-deleted",
    code: "D11",
    eyebrow: "HESAP SİLİNDİ",
    title: "Hesabın ve verilerin silindi",
    description: "trAI hesabın, özel fotoğrafların, prova sonuçların ve kombinlerin kalıcı olarak kaldırıldı.",
    tone: "success",
    symbol: "✓",
    primaryLabel: "Ana sayfaya dön",
    primaryHref: "/",
    detailTitle: "Oturum kapatıldı",
    detailText: "Aynı e-posta adresiyle daha sonra yeniden hesap oluşturabilirsin.",
    appScreen: false,
  },
];

export function getStatusState(slug: string) {
  return statusStates.find((state) => state.slug === slug);
}
